## 1）为什么需要异常处理机制？

Java异常是Java提供的一种识别及响应错误的一致性机制，java异常机制可以使程序中异常处理代码和正常业务代码分离，保证程序代码更加优雅，并提高程序健壮性。



## 2）异常的层次结构

### 1. Throwable

Throwable 是 Java 语言中所有错误与异常的超类。

Throwable 包含两个子类：Error（错误）和 Exception（异常），它们通常用于指示发生了异常情况。

Throwable 包含了其线程创建时线程执行堆栈的快照，它提供了 printStackTrace() 等接口用于获取堆栈跟踪数据等信息。

### 2. Error（错误）

Error 类及其子类：程序中无法处理的错误，表示运行应用程序中出现了严重的错误。

此类错误一般表示代码运行时 JVM 出现问题。通常有 Virtual MachineError（虚拟机运行错误）、NoClassDefFoundError（类定义错误）等。比如 OutOfMemoryError：内存不足错误；StackOverflowError：栈溢出错误。此类错误发生时，JVM 将终止线程。

### 3. Exception（异常）

#### Checked Exception

aka 编译异常，编译器要求必须处置的异常，是 RuntimeException 以外的异常，类型上都属于Exception类及其子类。

如果不处理，程序就不能编译通过。如 IOException、SQLException 等以及用户自定义的 Exception 异常（一般情况下不自定义检查异常）。

#### Unchecked Exception

RuntimeException 类及其子类异常，特点是 Java 编译器不会检查它，如 NullPointerException(空指针异常)、IndexOutOfBoundsException(下标越界异常)等。程序中可以选择捕获处理，也可以不处理，不影响编译通过。这些异常一般是由程序逻辑错误引起的，程序应该从逻辑角度尽可能避免这类异常的发生。

## 3）try-catch-finally

语法如下：

```java
try {                        
    //执行程序代码，可能会出现异常                 
} catch(Exception e) {   
    //捕获异常并处理   
} finally {
    //必执行的代码
}
```

举例：

```java
public static void main(String[] args) {
  FileInputStream fileInputStream = null;

  try {
    fileInputStream = new FileInputStream("abc.jpg");

    String s = null;
    s.toString(); // 这里会出现空指针异常

    //Stream 使用完需要关闭，因为Stream是占用资源的。
    //即使上面程序出现异常，流也必须要关闭，放在这里，流可能关不了。
    //fileInputStream.close();
  } catch (Exception e) {
    e.printStackTrace();
  } finally {
    System.out.println("hello everyone！"); //被执行了。
    //Stream 放在这里比较保险
    //finally中的代码一定会执行，即使try中出现了异常
    if (fileInputStream != null) { // 避免空指针异常
      try {
        fileInputStream.close();
      } catch (IOException e) { // close()的异常用try... catch...
        e.printStackTrace();
      }
    }
  }
}
```

其他：

```java
// try和finally，没有catch也可以一起使用。
try {
  System.out.println("try..."); // 第一步
  return; // 第二步，发现是return，先不执行；第四步
} finally {
  System.out.println("finally..."); // 第三步
}
// 后面不能写，因为不会被执行到。
// System.out.println("134");
```

```java
try {
  System.out.println("try...");
  System.exit(0); //退出JVM之后，finally语句中的代码就不执行了。
} finally {
  System.out.println("finally...");
}
```

## 4）try-with-resource

Java 7中引入的，自动释放资源。

优化上面的例子，代码会更简洁：

```java
public static void main(String[] args) {
  
  try (
  	FileInputStream fileInputStream = new FileInputStream("abc.jpg"); // 自动释放资源
  ) {
    
    String s = null;
    s.toString(); // 这里会出现空指针异常
    
  } catch (Exception e) {
    e.printStackTrace();
  } finally {
    System.out.println("hello everyone！"); //被执行了。
      }
    }
  }
```



## 5）自定义异常

创建两步：

- 第一步：编写一个类继承Exception或者RuntimeException

- 第二步：提供两个构造方法，一个无参数的，一个带有String参数的。

```java
public class MyException extends Exception{
    public MyException(){}

    public MyException(String s) {
        super(s);
    }
}
```



## 6）尽量捕获原始异常

捕获标准异常并包装为自定义异常是一个很常见的做法。这样可以添加更为具体的异常信息并能够做针对的异常处理。 在你这样做时，请确保将原始异常设置为原因（注：参考下方代码 NumberFormatException e 中的原始异常 e ）。Exception 类提供了特殊的构造函数方法，它接受一个 Throwable 作为参数。否则，你将会丢失堆栈跟踪和原始异常的消息，这将会使分析导致异常的异常事件变得困难。

```java
public void wrapException(String input) throws MyBusinessException {
    try {
        // do something
    } catch (NumberFormatException e) {
        throw new MyBusinessException("A message that describes the error.", e);
    }
} 
```



## 7）不要记录/打印堆栈后再抛出异常

可以发现很多代码甚至类库中都会有捕获异常、记录日志并再次抛出的逻辑。如下：

```java
try {
    new Long("xyz");
} catch (NumberFormatException e) {
    log.error(e);
    // 或者 
    // e.printStackTrace();
    throw e;
}
```

这个处理逻辑看着是合理的。但这经常会给同一个异常输出多条日志。如下：

```java
17:44:28,945 ERROR TestExceptionHandling:65 - java.lang.NumberFormatException: For input string: "xyz"
Exception in thread "main" java.lang.NumberFormatException: For input string: "xyz"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Long.parseLong(Long.java:589)
at java.lang.Long.(Long.java:965)
at com.stackify.example.TestExceptionHandling.logAndThrowException(TestExceptionHandling.java:63)
at com.stackify.example.TestExceptionHandling.main(TestExceptionHandling.java:58)
```

如上所示，后面的日志也没有附加更有用的信息。如果想要提供更加有用的信息，那么可以将异常包装为自定义异常。

```java
public void wrapException(String input) throws MyBusinessException {
    try {
        // do something
    } catch (NumberFormatException e) {
        throw new MyBusinessException("A message that describes the error.", e);
    }
}
```

因此，仅仅当想要处理异常时才去捕获，否则只需要在方法签名中声明让调用者去处理。

## 8）不要用异常处理机制代替判断

> 异常只应该被用于不正常的条件，它们永远不应该被用于正常的控制流。《阿里手册》中：
>
> 【强制】Java 类库中定义的、可以通过预检查方式规避的 RuntimeException 异常，不应该通过 catch 的方式来处理，比如：NullPointerException，IndexOutOfBoundsException等等。

比如，进行非空检查来避免 NullPointerException，检查 index 是否在数组的长度范围内 来避免 IndexOutOfBoundsException。

主要原因有三点：

- 异常机制的设计初衷是用于不正常的情况，所以很少会会JVM实现试图对它们的性能进行优化。所以，创建、抛出和捕获异常的开销是很昂贵的。
- 把代码放在try-catch中返回阻止了JVM实现本来可能要执行的某些特定的优化。
- 对数组进行遍历的标准模式并不会导致冗余的检查，有些现代的JVM实现会将它们优化掉。

## 9）不要过早捕获异常

如果盲目地过早捕获异常的话，通常会导致更严重的错误和其他异常。请看下面的例子。

```java
InputStream is = null;
try {
    is = new FileInputStream("沉默王二.txt");

} catch (FileNotFoundException e) {
    e.printStackTrace();
}

int b;
try {
    while ((b = is.read()) != -1) {
    }
} catch (IOException e) {
    e.printStackTrace();
}

finally {
    try {
        is.close();
    } catch (IOException e) {
        e.printStackTrace();
    }
}
```

假如文件没有找到的话，`InputStream` 的对象引用 is 就为 `null`，新的 `NullPointerException` 就会出现。

```java
java.io.FileNotFoundException: 沉默王二.txt (系统找不到指定的文件。)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at learning.Test.main(Test.java:12)
Exception in thread "main" java.lang.NullPointerException
    at learning.Test.main(Test.java:28)
```

`NullPointerException` 并不是程序出现问题的本因，但实际上它出现了，无形当中干扰了我们的视线。正确的做法是延迟捕获异常，让程序在第一个异常捕获后就终止执行。

## 10）优先捕获最具体的异常

> 大多数 IDE 都可以帮助你实现这个最佳实践。当你尝试首先捕获较不具体的异常时，它们会报告无法访问的代码块。

但问题在于，只有匹配异常的第一个 catch 块会被执行。 因此，如果首先捕获 IllegalArgumentException ，则永远不会到达应该处理更具体的 NumberFormatException 的 catch 块，因为它是 IllegalArgumentException 的子类。

总是优先捕获最具体的异常类，并将不太具体的 catch 块添加到列表的末尾。

你可以在下面的代码片断中看到这样一个 try-catch 语句的例子。 第一个 catch 块处理所有 NumberFormatException 异常，第二个处理所有非 NumberFormatException 异常的IllegalArgumentException 异常。

```java
public void catchMostSpecificExceptionFirst() {
    try {
        doSomething("A message");
    } catch (NumberFormatException e) {
        log.error(e);
    } catch (IllegalArgumentException e) {
        log.error(e)
    }
}
```

## 11）不要捕获 Throwable 类

> Throwable 是所有异常和错误的超类。你可以在 catch 子句中使用它，但是你永远不应该这样做！

如果在 catch 子句中使用 Throwable ，它不仅会捕获所有异常，也将捕获所有的错误。JVM 抛出错误，指出不应该由应用程序处理的严重问题。 典型的例子是 OutOfMemoryError 或者 StackOverflowError 。两者都是由应用程序控制之外的情况引起的，无法处理。

所以，最好不要捕获 Throwable ，除非你确定自己处于一种特殊的情况下能够处理错误。

> 参考链接：
>
> [Java：优雅地处理异常真是一门学问啊！](https://segmentfault.com/a/1190000021000956)
>
> [Java 基础 - 异常机制详解](https://pdai.tech/md/java/basic/java-basic-x-exception.html)

